In [10]:
#numpy basics

import numpy as np

a = np.array([1,3,6])

print(a)
print(a.shape)
print(a.dtype)
print(a.size)

[1 3 6]
(3,)
int32
3


In [5]:
b = a * np.array([2, 0, 4])
print(b)

[ 2  0 24]


In [12]:
l = [1,2,3]
l.append(4)
print(l)

a += np.array([4])
print(a)

[1, 2, 3, 4]
[ 9 11 14]


In [16]:
#dot product

l1 = [1, 2, 3]
l2 = [4, 5, 6]

a1 = np.array(l1)
a2 = np.array(l2)

dot = a1 * a2

print(dot)

sum = np.sum(dot)

print(sum)

print(a1 @ a2)

[ 4 10 18]
32
32


In [23]:
a = np.array([[1,2,4], [3,6,9], [4, 12, 16]])

print(a)
print(a.shape)
print(a.T)

print(np.linalg.inv(a))

print(np.linalg.det(a))

print(np.diag(a))

[[ 1  2  4]
 [ 3  6  9]
 [ 4 12 16]]
(3, 3)
[[ 1  3  4]
 [ 2  6 12]
 [ 4  9 16]]
[[-1.00000000e+00  1.33333333e+00 -5.00000000e-01]
 [-1.00000000e+00 -1.85037171e-17  2.50000000e-01]
 [ 1.00000000e+00 -3.33333333e-01 -1.38777878e-17]]
12.0
[ 1  6 16]


In [33]:
b1 = np.array([[1,2,3,4,5,6], [2,2,3,3,5,5]])

b2 = b1[:, 2]

print(b2)

b3 = b1 > 3
print(b3)

b4 = b1[b1>3]
print(b4)

b5 = np.where(b1>=3, b1, 0)
print(b5)

[3 3]
[[False False False  True  True  True]
 [False False False False  True  True]]
[4 5 6 5 5]
[[0 0 3 4 5 6]
 [0 0 3 3 5 5]]


In [44]:
c1 = np.array([1,2,3,4,5,6,7,8])

c2 = [2,4,6]
print(c1[c2])

even = np.argwhere(c1%2 == 0)
print("---------------")
print(c1)
print(even)
print(c1[even.flatten()])
print("---------------")

b1 = np.array([[1,2,3,4,5,6], [2,2,3,3,5,5]])

even = np.argwhere(b1%2 == 0)
print(even)
#doubt how to get even in 2d array
# print(b1[even.flatten()])

[3 5 7]
---------------
[1 2 3 4 5 6 7 8]
[[1]
 [3]
 [5]
 [7]]
[2 4 6 8]
---------------
[[0 1]
 [0 3]
 [0 5]
 [1 0]
 [1 1]]


In [49]:
a = np.arange(0,8)

print(a)
print(a.shape)

b = a.reshape((2,4))
print(b)
print(b.shape)

c = a[np.newaxis, :]
print(c)
print(c.shape)

d = a[:, np.newaxis]
print(d)
print(d.shape)

[0 1 2 3 4 5 6 7]
(8,)
[[0 1 2 3]
 [4 5 6 7]]
(2, 4)
[[0 1 2 3 4 5 6 7]]
(1, 8)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(8, 1)


In [56]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

c = np.concatenate((a,b))
print(c)

c = np.concatenate((a,b), axis = None)
print(c)

c = np.concatenate((a,b.T), axis = 1)
print(c)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
[[1 2 5]
 [3 4 6]]


In [59]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.hstack((a,b))
print(c)
d = np.vstack((a,b))
print(d)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [61]:
#broadcasting

x = np.array([[1,2,3],[4,5,6]])

y = np.array([1,1,1])

print(x+y)

[[2 3 4]
 [5 6 7]]


In [68]:
a = np.array([[5,6,7,8,9], [15,16,17,18,19]])
print(a)
print("---------sum-----------")
print(a.sum(axis=None))
print(a.sum(axis = 0))
print(a.sum(axis = 1))
print("---------mean-----------")
print(a.mean(axis=None))
print(a.mean(axis = 0))
print(a.mean(axis = 1))
print("---------var-----------")
print(a.var(axis=None))
print(a.var(axis = 0))
print(a.var(axis = 1))
print("---------std-----------")
print(a.std(axis=None))
print(a.std(axis = 0))
print(a.std(axis = 1))
# simialrly min and max

[[ 5  6  7  8  9]
 [15 16 17 18 19]]
---------sum-----------
120
[20 22 24 26 28]
[35 85]
---------mean-----------
12.0
[10. 11. 12. 13. 14.]
[ 7. 17.]
---------var-----------
27.0
[25. 25. 25. 25. 25.]
[2. 2.]
---------std-----------
5.196152422706632
[5. 5. 5. 5. 5.]
[1.41421356 1.41421356]


In [70]:
x = np.array([1,2,3], dtype=np.int16)
print(x)
print(x.dtype)

[1 2 3]
int16


In [72]:
#coping valus of array (default = is reference)

a = np.array([4,7,9])
b = a.copy()

b[0] = 5

print(a)
print(b)

[4 7 9]
[5 7 9]


In [81]:
#initializing arrays

a = np.zeros((2,3))
print(a)

b = np.ones((3,4))
print(b)

c = np.full((2,3), 5.0)
print(c)

d = np.eye(4)
print(d)

e = np.arange(12)
print(e) 

f = np.linspace(0, 10, 3)
print(f)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5. 5. 5.]
 [5. 5. 5.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0.  5. 10.]


In [90]:
#random nos between 0 and 1
print("-------- random nos between 0 and 1 -----------")
a = np.random.random((4,3))
print(a) 

#normal/gaussian disribution numbers with mean 0 and variance 1
print("-------- normal / gaussian disribution numbers with mean 0 and variance 1 -----------")
a = np.random.randn(4,3)
print(a)
print(a.mean(), a.var())

# random 10 ints with start at 3 and end at 9-1
print("-------- random ints with start at 3 and end at 9-1 -----------")
a = np.random.randint(3,9, size = 10)
print(a)

# random 10 ints with start at 0 and end at 9-1
print("-------- random ints with start at 0 and end at 9-1 -----------")
a = np.random.choice(9, size = 10)
print(a)

# random 10 ints with in [0,2,4,6,8]
print("-------- random ints in [0,2,4,6,8] -----------")
a = np.random.choice([0,2,4,6,8], size = 10)
print(a)

-------- random nos between 0 and 1 -----------
[[0.47760585 0.66498562 0.19299302]
 [0.28980665 0.93830005 0.16351098]
 [0.25835048 0.1859048  0.44375639]
 [0.66535133 0.09351029 0.66943081]]
-------- normal / gaussian disribution numbers with mean 0 and variance 1 -----------
[[ 1.21954697 -2.74773637  0.5501718 ]
 [-0.51466351 -0.8280132  -2.36379255]
 [-0.94103688 -1.91833542  0.32504211]
 [ 0.96741795 -0.6342245  -0.21804519]]
-0.5919724001945944 1.4774798535253286
-------- random ints with start at 3 and end at 9-1 -----------
[7 7 6 5 3 6 5 3 3 7]
-------- random ints with start at 0 and end at 9-1 -----------
[8 1 0 0 3 5 3 5 3 7]
-------- random ints in [0,2,4,6,8] -----------
[8 6 8 4 8 4 2 0 8 4]


In [91]:
# solving AX = b;

a = np.array([[1,1],[1.5,4]])
b = np.array([2200, 5050])

x = np.linalg.inv(a) @ b
print(x)

alternateWay = np.linalg.solve(a, b)
print(alternateWay)

[1500.  700.]
[1500.  700.]
